### ISSUE TITLE
Download status text has broken formatting

### ISSUE THREAD

**Issue by legofanlovessayori** [yurisuika/Zehn#22]
Might be language specific but if steam is set to german the download status text overlaps the main window a bit.

![image](https://github.com/user-attachments/assets/92160e37-7936-4bb0-9a3d-20ecf19c9506)

**Comment by yurisuika** [comment]
Ah, it looks like there may be a line wrap here because your language does not fit the fixed pixel spacing... It will require cutting off the text with ellipsis and stopping the overflow. The spacing is fixed because this is actually part of the button to the right, so it has to be a certain per-determined amount to the left and thus of the corresponding size. If I move it out of its parent element with JS, when Steam tries to remove the downloads bar when one has completed, it causes an error because it then cannot find that element, so this has to be the solution. If you'd like to enlarge this element, you would have to also move it farther left.

**Comment by yurisuika** [comment]
![image](https://github.com/user-attachments/assets/2af87f87-440a-4d11-899a-5c938416d18e)

So this is just the plain fix doing the cut off... What I can do, however, is add a variable to the config that you can adjust both the width and offset of the downloads bar in one swing.

**Comment by yurisuika** [comment]
![image](https://github.com/user-attachments/assets/a24cfe21-4b91-47d6-a6db-b759fb40cc9d)

Okay, so there we have the config option, it allows you to change the width of the downloads bar. Default is 200px, but you may adjust to as you see fit.
