### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by lingjiang233** [yurisuika/Zehn#25]
How to hide this avatar
![image](https://github.com/user-attachments/assets/ca727f32-f7e4-46ee-b8b3-694b292085c9)
Also, the avatar UI size in the friend list is incorrect
![image](https://github.com/user-attachments/assets/220c8054-a2fa-4a5a-a9b3-4cfc521968b1)

**Comment by yurisuika** [comment]
This may have been caused by using the wrong branch version? I have noticed that the beta branch was overwriting the stable branch in the releases, so apologies for that.

**Comment by yurisuika** [comment]
I think I see what happened. When there was the issue earlier this year that combining all branches into one was not compatible with the Millennium launcher auto-download feature, having deleted the other branches, I when recreating the beta branch I never changed the action export filename, so in the past month or so that I've been working on the beta branch, it has been releasing with a title for the stable branch.
